use assignment;

INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")

INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "ML Engineer", 4000000, "머신러닝 엔지니어", "Tensorflow")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO board(id, position, reward, content, tech) VALUES(2, "Frontend Engineer", 3400000, "프론트엔드 엔지니어", "Javascript")
INSERT INTO user VALUES(2, "h970126", "황승수", 26)